class Story {
    constructor() {

    }
}

var m = new Story();

export var m;


m.intro = `<p>Thank you for agreeing to participate in this experiment!<br>
<br>In this experiment, you will play a short mystery game. You will be able to direct the investigation, and after exploring a certain number of options, you will be prompted to make your final guess for the solution.<br><br>On each page, there will be three textboxes available to you: One is free space for you to take notes to keep track of any details you think might be relevant. This box is persistent, so you will be able to access and edit your earlier notes on every page of the game. <br>
<br>The second box asks you to describe your theories about what might have happened, and to <b>include your percentage confidence that the theory is correct</b> (for example, 30% confident, 70% confident, and so on). Please do not forget to include your percentage confidence! You may suggest multiple theories (and provide different confidence levels for them). You may describe complete explanations, or just theories about certain elements. Your percentages need not sum to 100. This box’s contents will not persist from one page to the next. You don’t need to re-describe theories that haven’t changed at all, but <b>if your percentage confidence changes, please refer to the earlier theory and provide an update</b>. 
<br><br>The third box asks you to briefly explain your reasoning for clicking the next link. <br><br>At the end of the experiment, your data will download to your browser in a JSON file. <b>Please save this file and email it to me!</b> Otherwise your data will not be saved! <br><br>A week after the experiment, I will contact you with some short additional surveys, after which I will share the purpose of the experiment.</p>`;

m.introduction = `<p>This holiday season, you and your friend Frances struck a deal. You&rsquo;d come with her on a family-mandated New Year&rsquo;s vacation to visit her aunt, uncle, and cousin, where you could enjoy staying in their big house on a countryside lake, and eat all the Christmas leftovers you could want. In return, you&rsquo;d provide some more pleasant company for her than she&rsquo;s learned to expect from this side of the family&mdash;who, apparently, are constantly at each other&rsquo;s throats.<br /><br />Unfortunately things went wrong immediately. First, a huge winter storm hit as you were driving out. You took several wrong turns and had to dig your car out of a snowbank. In the end, though the snowfall ended around 7:00, you didn&rsquo;t arrive at the house until after midnight, at which point you fell into a deep sleep in the guest room.<br />
<br />Then, you were awakened the next morning by the sounds of crashing and shouting. You rushed downstairs to find that Frances&rsquo;s uncle Victor had died during the night&mdash;and under very suspicious circumstances.<br /><br />Thanks to the blizzard, the police won&rsquo;t be able to get to the house until the next day. Luckily, you are a straight-A student in your senior year at Private Detective Academy&mdash;home to famous alumni such as Sherlock Holmes, Hercule Poirot, and Nancy Drew. You&rsquo;ve talked to the local police chief over the phone, and been charged with carrying out the investigation to the best of your ability.</p>`;
//Investigation sequence

m.body_intro = `<p>Cool air greets you as you enter Victor&rsquo;s bedroom. Per your instructions, the room has been disturbed as little as possible.</p>
<p>The most noticable thing in the room is the body lying in the center&mdash;face down, with a large gash in his forehead head, which rests near the bloodstained front hearth of the fireplace. Stepping back, other unusual aspects of the room become clear. Several vases and a lamp have been smashed, books and papers lie toppled and scattered around the room, and patches of dried mud spot the floor.</p>
<p>You note the other fixtures of the room. Like the rest of the house, the bedroom is old and somewhat idiosyncratic. It&rsquo;s a large and spartan space, with a slightly uneven floor and off-center fireplace set in its back wall. It&rsquo;s in the basement of the house, so there are only two small windows, both set high in the back wall, through which the base of the snow-covered garden shrubs are visible.</p>
<p>Frances lingers in the doorway. &ldquo;Is there anything I can do to help?&rdquo;</p>
<p>&ldquo;Is this room exactly how you found it?&rdquo; you ask.</p>
<p>&ldquo;I think so?&rdquo; says Frances. &ldquo;It&rsquo;s possible something was moved when I ran to call the police.&rdquo;</p>
<p>&ldquo;And who was here when you found it?&rdquo;</p>
<p>&ldquo;All three of us. Me, my aunt Melissa, who is&mdash;who was married to Victor, and their son&mdash;my cousin&mdash;Nathan.&rdquo;</p>
<p>You take another look at the door, and note that the handle and lock have been smashed through. &ldquo;Did you find the lock like this?&rdquo;</p>
<p>&ldquo;Ah, no. When Victor didn&rsquo;t respond to our calls to his bedroom landline, Nathan broke open the door.&rdquo;</p>
<p>&ldquo;Just because he didn&rsquo;t answer his phone? Didn&rsquo;t you say he was hard of hearing?&rdquo;</p>
<p>Frances nods. &ldquo;Yes, but he never slept this late. It was odd that he wasn&rsquo;t up by seven-thirty, and we knew something must be wrong when he wasn&rsquo;t up by nine.&rdquo;</p>`

m.body_bodyL = `Investigate the body`;
m.body_vasesL = `Investigate the vases`;
m.body_mudL = `Investigate the mud`;
m.body_windowsL = `Investigate the windows`;
m.body_lockL = `Investigate the lock`;
m.body_fireplaceL = `Investigate the fireplace`;
m.body_lightL = `Investigate the light`;
m.body_returnL = `Return`;
m.body_exitL = `Proceed to reading the family's statements`;

m.body_body = `<p>You kneel down to further examine the body. A cursory search reveals no injuries other than the head wound; which is certainly deep enough to have been fatal. The shape of the wound matches the sharp corner of the hearth. The body lies prone, implying he fell directly forward. He&rsquo;s not wearing his hearing aids, or his glasses.</p>
<p>&ldquo;Was he ever prone to fainting or losing his balance?&rdquo; you ask. A fall alone could have killed him, but wouldn&rsquo;t explain the wreckage. And people rarely fall directly forward.</p>
<p>But Frances shakes her head firmly. &ldquo;No, never. He was very nearsighted and hard of hearing, but he had no other health or balance issues. And he was meticulous about wearing his glasses and hearing aids whenever he left the bedroom.&rdquo;</p>
<p>So a fall is unlikely. He could have tripped, in theory, but looking around you see nothing he could have tripped over. This leaves the possibility that he could have been pushed. Judging by his size, you&rsquo;d guess it would have taken some force. At any rate it would have been impossible to do by accident. The intention may not have been to kill him&mdash;but if he was pushed, he was pushed hard, by someone standing directly behind him, into a hard stone fixture. The intent must at least have been to maim.</p>`;

m.body_vases = `<p>The vase shards and books lie scattered on the floor, mostly at the base of the desk and nighttable. The papers, meanwhile, are scattered all over the room.</p>
<p>You find among the disorder a number of black hairs of 3-4 inches. You glance at Victor&mdash;his hair is short and grey, so they&rsquo;re definitely not his.</p>`;

m.body_mud = `<p>Unfortunately you don&rsquo;t find anything as damning as a shoeprint. In fact, the scuffs are curiously featureless. You note a couple small roundish smudges, but can&rsquo;t recall having seen anything like them in your 200-level footprint identification class.</p>
<p>How the dirt got here is its own question. There was none in the hall, or by the doorway. There&rsquo;s a little on Victor&rsquo;s back, but none on his shoes.</p>`;

m.body_windows = `<p>The windows are set back in the wall, and open outwards. There is no screen, but they look a little too small for a person to fit through. A very small person or child might manage to squeeze through.</p>
<p>Looking out, you find the windows are set only six or seven inches above the ground outside. The view isn&rsquo;t much&mdash;all you can see through them is the base and roots of some of the garden hedges.</p>
<p>The windows are both shut and locked from the inside.</p>`;

m.body_lock = `<p>The lock has been thoroughly smashed. &ldquo;Was this lock operated with a key?&rdquo;</p>
<p>&ldquo;Technically yes, but Victor lost it over a year ago, and no one&rsquo;s seen it since,&rdquo; says Frances. &ldquo;Without the key, it can only be locked and unlocked from the inside. That&rsquo;s why we had to smash it open.&rdquo; After a moment she adds &ldquo;There are several others like this in the house if you want to look at one later.&rdquo;</p>`;

m.body_fireplace = `<p>It’s an old, utilitarian fireplace of bare stone. A pile of wood next to it suggests regular use. Indeed, the charcoal and ash looks very recent—it was probably in use last night.</p>`;

m.body_light = `<p>You look around for a light switch and instead find a small console next to the door. It&rsquo;s the most modern-looking thing in the room.</p>
<p>&ldquo;It&rsquo;s a motion sensing light,&rdquo; Frances explains. &ldquo;Victor hated having to get up to turn the light off when he was reading in bed. He had it set to turn off after five minutes if it doesn&rsquo;t detect any movement.&rdquo;</p>
<p>You navigate to the settings, and find that it actually says when they were last changed&mdash;eight months ago. No one has tampered with this light.</p>`;

m.body_return = `<p>What to examine next?</p>`;






m.statements = `<p>First you read the statement written by Nathan, Melissa and Victor&rsquo;s adult son:<br /><i>Nathan movements:<br />Yesterday:<br />12:00pm- Arrived at the house from airport<br />~6:50- Took business call in bedroom. Victor was still awake in the sitting room when I left.<br />~8:10- Call ended. Went to bathroom a few minutes later &amp; noticed through the door crack that Victor&rsquo;s bedroom light was already out.<br />~11:00- Went to sleep, after working in bedroom rest of evening.<br />This morning:<br />~8:00- Got up<br />9:00- Decided it was concerning Victor wasn&rsquo;t awake yet. Door was locked &amp; cold draft came under the door, so I broke it open.</i><br />
<br />Next is Frances&rsquo;s statement:<br /><i>Yesterday evening:<br />- We were all together in the sitting room at 6:30. Nathan left the room before 7:00. Victor left not long after that.<br />- I took Peanut for a walk in the snow at 7:30. I went to the far side of the lake. (Gorgeous views!)<br />- On my way back, I noticed the light in Victor&rsquo;s window was already out. This was at 8:14. I noticed the time because I thought it was unusual he was in bed that early.<br />- I went inside at 8:20 and didn&rsquo;t see anyone else the rest of the night.<br />This morning:<br />- Everyone was awake by 8:20. We were getting concerned about Victor, since he always gets up at 7:30 exactly.&nbsp;<br />- At 9:00 we forced our way into his room.</i>
<br /><br />Last, you read the statement written by Melissa, Victor&rsquo;s wife.<br /><i>Last night:<br />6:30: All 4 of us were gathered in the sitting room.<br />About 6:50: Nathan left to take a call.<br />About 7:00: Victor left to go to his room for the night.<br />About 7:30: Frances went outside for a walk.<br />About 7:40: I heard Nathan shouting from down the hall.<br />About 8:20: Frances returned from her walk.<br />This morning:<br />About 9:00: After Victor failed to answer his phone, we broke into his room.</i></p>`;


m.inv_menu = `You reflect a moment and consider what it will be most fruitful to investigate next. <b>NOTE: You will be able to explore a limited number of options, so prioritize accordingly. New options may be unlocked as you investigate.</b>`;

m.vince_intro = `<p>Victor&rsquo;s son Nathan is a tall and broad man with short brown hair about 30 years old. He&rsquo;s busily working on his laptop in the study, and doesn&rsquo;t seem pleased when you interrupt him.<br /><br />He sweeps you up and down with his gaze, and scowls. &ldquo;And this will take how long?&rdquo;&nbsp;<br /><br />&ldquo;I just need to ask a few questions,&rdquo; you say.<br /><br />He shuts his laptop with force, and swings his chair around to face you. &ldquo;Be quick about it. I don&rsquo;t have all day.&rdquo;</p>`;
m.vince_call = `<p>&ldquo;I was talking to my secretary, Ferris,&rdquo; he replies. &ldquo;And I&rsquo;m not telling you anything more than that. It&rsquo;s for an upcoming project, and I don&rsquo;t go around dropping company secrets to anyone with a clipboard.&rdquo;<br /><br />&ldquo;Were you on the phone the whole time from 6:50 to 8:10?&rdquo; you ask.<br /><br />&ldquo;Yes.&rdquo;<br /><br />&ldquo;And you stayed in your bedroom?&rdquo;<br /><br />&ldquo;Yes, I had to take it in there to get away from Frances&rsquo;s untrained dog,&rdquo; he says irritably. &ldquo;And you&rsquo;ll see it was a landline&mdash;this hovel doesn&rsquo;t have cell service&mdash;so obviously I couldn&rsquo;t have left the room while this was happening.&rdquo;<br /><br />You remember passing Nathan&rsquo;s guest room earlier. &ldquo;Victor&rsquo;s bedroom is right next to yours. You didn&rsquo;t hear anything unusual?&rdquo;<br /><br />&ldquo;No. I was concentrating on the call.&rdquo;</p>`;
m.vince_shout = `<p>&ldquo;I told you, I was on the phone,&rdquo; he huffs. &ldquo;And I wasn&rsquo;t getting my point across. You know how it is.&rdquo;</p>`;
m.vince_lock = `<p>&ldquo;He locked it sometimes to keep the door shut,&rdquo; shrugs Victor. &ldquo;The door wouldn&rsquo;t shut otherwise. Is that all?&rdquo;</p>`;
m.vince_window = `<p>You check your notes. &ldquo;You mention in your statement that there was a cold draft coming in under the door. Was the window was open when you arrived this morning?&rdquo;<br /><br />Nathan nods. &ldquo;Melissa shut it when we went in there. It&rsquo;s freezing out.&rdquo;<br /><br />&ldquo;Did he often sleep with the window open?&rdquo; you ask.<br /><br />&ldquo;Not really. He sometimes opened it when it got too hot indoors&mdash;the heating in this old house is unreliable. But not overnight. Is that all?&rdquo;</p>`;
m.vince_lake = `&ldquo;You can sprint back to the house from the lake in under ten minutes if you push it,&rdquo; Nathan says.&nbsp;`;
m.vince_health = `<p>&ldquo;She&rsquo;s been sick off and on since I was young,&rdquo; Nathan says. &ldquo;She&rsquo;s used to managing it, and she&rsquo;s certainly not on her deathbed. Getting the insurance to cover things is the hardest part. They often don&rsquo;t.&rdquo;<br /><br />&ldquo;How physically capable would you say she is?&rdquo; you ask.<br /><br />&ldquo;Not likely to push over someone Victor&rsquo;s size if that&rsquo;s what you&rsquo;re asking,&rdquo; he snorts. &ldquo;Mind you, if she wanted to kill him, I&rsquo;m sure she could be more creative than that.&rdquo;</p>`;
m.vince_marriage = `<p>&ldquo;Is this really relevant?&rdquo; snaps Nathan. &ldquo;Everyone knows they&rsquo;ve been at each other&rsquo;s throats for years.&rdquo;</p>`;
m.vince_key = `<p>Nathan huffs. &ldquo;I couldn&rsquo;t tell you about the key, I don&rsquo;t live here. Is that all?&rdquo;</p>`;
m.vince_cutscene = `<p>Nathan seems pleased by your preparing to leave, but then looks up. &ldquo;You ought to know&mdash;Victor was really having a go at Frances yesterday.&rdquo;<br /><br />&ldquo;Oh? When was this?&rdquo;<br /><br />&ldquo;I had my window open when she pulled up in the drive around two,&rdquo; he says. &ldquo;Apparently she changed her major to&hellip; you know, one of those ridiculous new ones like high altitude basket weaving or something. Victor found out from a friend when he was visiting the college and threatened to tell her parents.&rdquo;<br /><br />&ldquo;She hadn&rsquo;t told them?&rdquo; Not surprising&mdash;she hadn&rsquo;t told you yet either. This is the first you&rsquo;re hearing of it.<br /><br />&ldquo;Hah, definitely not. They&rsquo;re dead set on her studying law, and she&rsquo;s a pushover. She said she couldn&rsquo;t afford school without their help, and begged Victor not to say anything.&rdquo;<br /><br />&ldquo;And how did he respond?&rdquo;<br />&nbsp; &nbsp;&nbsp;<br />&ldquo;Don&rsquo;t know,&rdquo; he shrugs. &ldquo;They went inside at that point, and I haven&rsquo;t thought about it since.&rdquo; He turns back to his laptop at this&mdash;clearly the conversation is over.</p>`;

m.fran_intro = `<p>You find Frances reading in the library, curled up on a beanbag, absently scratching her dog Peanut who&rsquo;s curled up in front of the nearby radiator. She smiles when she sees you. &ldquo;How&rsquo;s the investigation going?&rdquo;<br /><br />&ldquo;Still in the early stages,&rdquo; you say. &ldquo;Mind if I ask a few questions?&rdquo;<br /><br />&ldquo;Please,&rdquo; she replies, putting her book down.</p>`;
m.fran_marriage = `<p>Frances hesitates. &ldquo;Well, he and Aunt Melissa have been cold with each other for years. They split up the rooms of house, and go most days barely speaking.&rdquo;<br /><br />&ldquo;But they stayed married?&rdquo;<br /><br />&ldquo;Victor&rsquo;s religious. And he has an ironclad prenup. Melissa doesn&rsquo;t work, and she&rsquo;s treating her health condition on his healthcare, so she couldn&rsquo;t afford a divorce.&rdquo;`;
m.fran_health = `<p>&ldquo;She has a degenerative muscular condition,&rdquo; replies Frances. &ldquo;It&rsquo;s treatable but not curable. I&rsquo;m afraid I don&rsquo;t know any more.&rdquo;</p>`;
m.fran_lake = `<p>&ldquo;I was at the far end&hellip; around eight? Oh wait, I took several pictures and they&rsquo;re timestamped.&rdquo;<br />Indeed, when she shows you her phone you see the last photo in her camera roll&mdash;a selfie&mdash;firmly timestamped at 7:55.<br /><br />&ldquo;And you didn&rsquo;t get back inside the house until 8:20?&rdquo;<br /><br />&ldquo;That&rsquo;s right. It wouldn&rsquo;t usually take so long, but the snow made it much slower. Then it took another five minutes or so for Peanut and I to get our coats, hats, and boots off.&rdquo;</p>`;
m.fran_cutscene = `<p>As you prepare to leave Frances hesitates. &ldquo;Listen, um&hellip; I might know about something that might be relevant.&rdquo;<br /><br />You&rsquo;re instantly alert. &ldquo;Oh?&rdquo;<br /><br />Frances hesitates again. &ldquo;I mean&hellip; there were always rumors that Victor was cheating on Melissa. I never put much stock in them.&rdquo;<br /><br />&ldquo;But&hellip;?&rdquo;<br /><br />She makes a face and then speaks. &ldquo;I&hellip; I saw him getting lunch in town with Ms. Giles, one of the school administrators a few weeks ago. They were acting&hellip; very friendly with each other.&rdquo;<br /><br />&ldquo;Friendly as in&hellip;?&rdquo;<br /><br />&ldquo;He&hellip; kissed her on the cheek. Which I&rsquo;ve never seen him do.&rdquo; She shakes her head. &ldquo;But I don&rsquo;t want to jump to the worst conclusion without cause. There could be an innocent explanation.&rdquo;</p>`;

m.mel_intro = `<p>You find Melissa in a well-heated sunroom, carefully examining a sudoku puzzle. She is a tall but somewhat frail-looking woman with short black hair and a focused gaze. A cane with a yellow tennis ball stuck on its end rests near the couch about a foot away from her.<br /><br />&ldquo;Before we begin, let me express my condolences,&rdquo; you say. &ldquo;I&rsquo;m so sorry for your loss.&rdquo;<br /><br />Unexpectedly Melissa chuckles. &ldquo;I appreciate your politeness, but there&rsquo;s no need to spare my feelings. Victor and I have not been in love for quite some time.&rdquo;</p>`;
m.mel_move = `<p>You check your notes. &ldquo;According to these statements, you were alone between 7:30 and 8:20?&rdquo;<br /><br />&ldquo;That&rsquo;s right. And I don&rsquo;t have anyone who can confirm that, I&rsquo;m afraid. But it&rsquo;s quite clear I couldn&rsquo;t have harmed Victor.&rdquo;<br /><br />&ldquo;Why&rsquo;s that?&rdquo;<br /><br />Melissa rises to her feet slowly, arms and legs quivering, as she grips the table for balance. &ldquo;Do I look like I could have pushed Victor over?&rdquo; She lowers herself back into her seat. &ldquo;I would encourage you to call my doctors to confirm my physical capabilities. I&rsquo;ll give them permission to speak to you.&rdquo;</p>`;
m.mel_lock = `<p>&ldquo;The door wouldn&rsquo;t stay shut unless it was locked, so he had to periodically,&rdquo; says Melissa. &ldquo;But it&rsquo;s not likely he would have done that last night.&rdquo;<br /><br />&ldquo;No?&rdquo;<br /><br />&ldquo;It wasn&rsquo;t cold enough,&rdquo; replies Melissa. &ldquo;His fireplace keeps the room much too warm.&rdquo;</p>`;
m.mel_window = `<p>&ldquo;He sometimes left it open when it was too hot indoors,&rdquo; Melissa replies. &ldquo;Our heating is erratic.&rdquo;</p>`;
m.mel_lake = `<p>Melissa chuckles dryly, and indicates her cane. &ldquo;As you can imagine, I don&rsquo;t get out there much. I couldn&rsquo;t say.&rdquo;</p>`;
m.mel_health = `<p>&ldquo;He was quite healthy,&rdquo; she says. &ldquo;No balance issues at all. He&rsquo;s quite blind and deaf without his hearing aids and glasses, but he never leaves his bedroom without them. He was not a frail man. I&rsquo;ve never known him to fall, and he would not have been easy to push.&rdquo;<br /><br />&ldquo;He wasn&rsquo;t wearing his glasses or hearing aids,&rdquo; you remember. &ldquo;Could he have tripped on something?&rdquo;<br /><br />She considers. &ldquo;It&rsquo;s certainly possible, but on what? We found nothing in the room.&rdquo;<br /><br />You make a note. &ldquo;And he hadn&rsquo;t been acting strange at all?&rdquo;<br /><br />&ldquo;Let&rsquo;s me think&hellip; he spent most of the afternoon complaining vigorously about politics, my niece&rsquo;s dog, and everything wrong with today&rsquo;s youths, so no, I didn&rsquo;t notice anything was at all unusual.&rdquo;</p>`;
m.mel_key = `<p>&ldquo;Yes, it&rsquo;s been missing for quite some time,&rdquo; says Melissa. &ldquo;No one&rsquo;s seen it since last year.&rdquo;</p>`;
m.mel_cutscene = `<p>Melissa stops you before you leave. &ldquo;There&rsquo;s one other thing you ought to know,&rdquo; she says. &ldquo;I overheard an argument between Victor and Nathan yesterday afternoon.&rdquo;<br /><br />&ldquo;About something serious?&rdquo;<br /><br />&ldquo;Depends on your perspective,&rdquo; Melissa says dryly. &ldquo;Victor threatened to cut Nathan out of his will.&rdquo;<br /><br />&ldquo;That does sound serious.&rdquo;<br /><br />&ldquo;Not financially,&rdquo; responds Melissa. &ldquo;With his line of work, I assume Nathan is far wealthier than we are. Our assets are entirely tied up in the house, and it&rsquo;s in need of a good deal of work.&rdquo;&nbsp;<br /><br />You nod, making a note. &ldquo;How did Nathan respond?&rdquo;<br /><br />When Melissa speaks, it&rsquo;s in a much cooler tone of voice. &ldquo;He said some very uncivilized words, and told Victor to do something very specific.&rdquo;<br /><br />&ldquo;Ah.&rdquo;<br /><br />She shakes her head. &ldquo;I didn&rsquo;t raise him to speak to his elders that way, but Nathan unfortunately takes after his father in most ways.&rdquo;</p>`;

m.secretary = `<p>After a bit of digging, you find Nathan&rsquo;s office&rsquo;s phone number online. You punch in the number and wait. Finally, his secretary Ferris picks up.<br /><br />&ldquo;Yes, I recorded the call,&rdquo; says Ferris. &ldquo;He got on at 6:55, and hung up at 8:12.&rdquo;<br /><br />&ldquo;And you didn&rsquo;t hear anything unusual or notice him acting oddly? For example, he never stepped out for a minute?&rdquo;<br /><br />&ldquo;No. Much as I might have wished,&rdquo; Ferris mutters under his breath. &ldquo;I can send you the recording.&rdquo;<br /><br />You skip through the recording at 15 second intervals, and find, indeed, that Nathan was speaking or yelling for pretty much the entire duration, without any major breaks.</p>`;
m.doctor = `<p>With Melissa&rsquo;s permission the hospital is willing to send you her records, but that doesn&rsquo;t mean they make it easy for you. You call several departments, and wind up having to make an account on their website before they&rsquo;re able to send you the records of her diagnosis and capabilities. (Fortunately they&rsquo;re legitimate&mdash;you learned how to verify this in Forged Document Detection 110.)<br /><br />When you do get your hands on them, they&rsquo;re consistent with Melissa&rsquo;s story: she&rsquo;s encouraged to minimize walking, and avoid lifting heavy objects. She consistently has difficulty standing and opening doors. From her strength assessment, it&rsquo;s clear she couldn&rsquo;t have pushed over someone Victor&rsquo;s size.</p>`;
m.lake = `<p>Frances&rsquo;s photos confirm that she was on the other side of the lake at 7:55, and Nathan&rsquo;s testimony suggests that Victor had already been dead for five minutes&mdash;long enough for the motion-sensing light to go out&mdash;by 8:14. That means if Frances is guilty, she had fourteen minutes to get from the lake to Victor&rsquo;s room.<br /><br />You get all your snow gear on and trek out to the other side of the lake. Then, you run back to the house as quickly as you can. It&rsquo;s very slow going&mdash;the snowfall means you can&rsquo;t travel much faster than walking. After fourteen minutes, you&rsquo;re just arriving back at the driveway. It takes you another five minutes to let yourself in and navigate to Victor&rsquo;s bedroom. Even if the snow had been a little less deep, Frances certainly couldn&rsquo;t have made it back and attacked Victor in that time.</p>`;
m.lawyer = `<p>Fortunately you find that Victor keeps his lawyer&rsquo;s phone number in his study rather than his desk drawer, so you don&rsquo;t have to tamper with the crime scene. His lawyer starts to say that his office isn&rsquo;t open today, but agrees to help you when you explain why you&rsquo;re calling.<br /><br />&ldquo;Yes, he called me yesterday to make an appointment to update it,&rdquo; says the lawyer. &ldquo;He wanted to remove his son from the will, and leave his half of the inheritance to his alma mater instead.&rdquo;<br /><br />&ldquo;But he hadn&rsquo;t done it yet?&rdquo;<br /><br />&ldquo;No. So it seems Nathan will still get his half.&rdquo;<br /><br />You ask a few follow up questions, but nothing else strikes you as relevant. You thank him for his time.</p>`;
m.roommate = `You’re friendly with Frances’s college roommate, so she’s not surprised when you give her a call. Frances has already told her about Victor’s death, so she’s happy to help in any way you can. When you bring up the subject of Frances’s finances, you manage to do it in a way that doesn’t come across as weird.

“Yes, she’s been really worried about how her parents are taking her academic situation. They didn’t want her to go to this school at all. She’s been wanting to change her major, but they said they’d pull her out of school if she did.”`;
m.affair = `<p>Ms. Giles is a university administrator, so you&rsquo;re able to find her phone number on the school website. You&rsquo;re relieved to learn that she already heard about Victor&rsquo;s death, and express your condolensces.<br /><br />&ldquo;How well did you know him?&rdquo; you ask.<br /><br />Giles laughs, somewhat bitterly. &ldquo;You mean, was I having an affair with him?&rdquo;<br /><br />&ldquo;Er&hellip;&rdquo;<br /><br />&ldquo;Yes, we were seeing each other casually,&rdquo; she says. &ldquo;Nothing committed. I had no idea he was married until earlier today, and I would not have been involved with him if I had.&rdquo;<br /><br />You ask a few more questions and then end the call, preferring not to bother her too much after such an unpleasant set of news.</p>`;
m.company = `What should have been one of the easiest investigative tasks before you turns out to be a major headache. The company website is so full of buzzwords and conflicting statements, you can’t even figure out what they’re selling after reading the entire home page. They’re billing themselves as an AI-based biotechnical injury lawfirm, whatever that means.`;
m.window = `<p>After putting on your jacket and boots, you trudge through the snow to investigate the outside of Victor&rsquo;s window. The bulk of snow fell yesterday during the day, before any of this occured. A dusting of snow from early in the morning obscures the animal tracks all throughout the garden, but it&rsquo;s clear at a glance that no person made it anywhere near Victor&rsquo;s window last night&mdash;the snowdrifts would have been far more disturbed than the merely moderate scuff marks you see.<br /><br />Crouching down, you peer into Victor&rsquo;s room. His bed is about six inches below the window, and his desk up against the wall. His back would have been to the windows while he worked.<br /><br />Before going outside, you left an identical window unlocked in another guest room to test whether it could have been an entry point. After trying for a few minutes, you find that you can&rsquo;t squeeze through. Getting your feet through is no issue, since it&rsquo;s less than a foot off the ground. But it&rsquo;s too small for you to fit through all the way. You&rsquo;re no bigger than the other inhabitants of the house, so that rules them out too.</p>`;
m.boots = `You go through all the boots in the tray and compare them to the pictures you took of the crime scene. You don’t see any prints that even remotely resemble the marks you saw in Victor’s bedroom.`;
m.lock = `<p>You find an empty guest room, and experiment with the lock and its corresponding key. Without using the key, it&rsquo;s lockable and unlockable only from the inside. With they key, it can be locked and unlocked from the outside as well.<br /><br />On a whim, you test the spare key on Victor&rsquo;s door, but it doesn&rsquo;t work. It looks like all these guest rooms have unique keys, and only the original would suffice.</p>`;
m.cell = `You give it several tries, but all of the calls you attempt to place from various parts of the house fail to land. The landline is definitely the only way to have a phone call with someone.
`;

m.confrontation = `<p>You're inrerrupted from your latest investigation by Nathan entering the room. The remaining members of the household enter behind him, apparently unsuccessfully trying to talk him out of something. <br><br> &ldquo;Alright, you&rsquo;ve had your chance to look around,&rdquo; he says. &ldquo;Now tell us what you've learned.&rdquo;<br />
<br />&ldquo;I&rsquo;ve only been working on this for a couple hours,&rdquo; you object.<br /><br />&ldquo;Plenty of time to rearrange all the evidence to your liking,&rdquo; says Nathan. &ldquo;How do we know YOU didn&rsquo;t kill him?&rdquo;<br /><br />Melissa rubs her forehead. &ldquo;Nathan, don&rsquo;t be ridiculous.&rdquo;<br /><br />&ldquo;What&rsquo;s so ridiculous about it?&rdquo; he demands. &ldquo;The door was locked. None of the three of us could have done it. But this stranger was suspiciously late to arrive and lurking around outdoors late at night.&rdquo; He rounds on you. &ldquo;Who&rsquo;s to say you didn&rsquo;t get here at 8:00 after all, let yourself in through the window, and wait outside for a few hours to announce you&rsquo;d arrived?&rdquo;<br />
<br />&ldquo;Why in the world would I do that?&rdquo; you protest.<br /><br />&ldquo;There&rsquo;s absolutely nothing to suggest that,&rdquo; argues Frances.<br /><br />&ldquo;You&rsquo;ve had plenty of time to investigate,&rdquo; Nathan says, still addressing you. &ldquo;Now you can tell us what you&rsquo;ve found, and then you can get back to your school, and we&rsquo;ll wait for a real professional to show up.&rdquo;
<br><br><b>Please make a complete final guess in the theories section!</b></p>`;
m.reveal = `<p>You take a deep breath. &ldquo;I have a theory. I can&rsquo;t prove that it happened this way, but this is the explanation most of the evidence points to. I think Victor&rsquo;s death was an accident.&rdquo;<br /><br />Silence&mdash;you&rsquo;ve surprised everyone. &ldquo;What about the smashed vases and books?&rdquo; asks Frances.<br />
<br />&ldquo;I repeat my earlier assessment that Victor did not have any balance issues,&rdquo; says Melissa.<br /><br />&ldquo;No, but you did concede he could have tripped on something,&rdquo; you say. &ldquo;I think he did trip on something that later moved.&rdquo;<br /><br />Nathan raises an eyebrow. &ldquo;Moved? You mean was moved by someone else.&rdquo;<br /><br />&ldquo;Ah. Uh, no, not exactly.&rdquo; You hesitate. &ldquo;There were a number of black hairs among the wreckage in Victor&rsquo;s room.&rdquo;<br /><br />There&rsquo;s a moment of silence, then Frances gasps. &ldquo;No&mdash;not Peanut?&rdquo;<br /><br />&ldquo;That can&rsquo;t be right,&rdquo; says Melissa. &ldquo;The door was locked from the inside. Peanut couldn&rsquo;t have gotten in.&rdquo;<br /><br />&ldquo;He could have fit through the window.&rdquo; You turn to Frances. &ldquo;Was Peanut with you the whole time on your walk?&rdquo;<br /><br />&ldquo;I&mdash;no, he never is,&rdquo; she says, eyes wide. &ldquo;He runs all over the place, but he always meets up with me back at the house. I didn&rsquo;t see him at all while I was on the far side of the lake.&rdquo;<br />
<br />&ldquo;So&mdash;Peanut runs around for a few minutes, and then gets cold,&rdquo; says Melissa. &ldquo;He finds the heat coming out of Victor&rsquo;s window. He jumps down onto the bed, and curls up in front of the fireplace.&rdquo;<br /><br />&ldquo;I&rsquo;d guess that&rsquo;s why the door was locked in the first place,&rdquo; you say. &ldquo;Peanut might have tried following Victor into his room to get at his fire. So Victor locked the door to keep him out, and opened the window to let out the excess heat.&rdquo;<br /><br />&ldquo;Only for Peanut to come in through that window once he and Frances left on their walk,&rdquo; concludes Melissa. &ldquo;And Victor doesn&rsquo;t hear any of this because he&rsquo;s not wearing his hearing aids.&rdquo;<br /><br />You nod. &ldquo;And he&rsquo;s not wearing his glasses, so he doesn&rsquo;t see him when he stands up to go stoke the fire.&rdquo;<br /><br />Nathan speaks next. &ldquo;Peanut doesn&rsquo;t realize he&rsquo;s been tripped over, he just thinks he&rsquo;s been kicked again. So he jumps around the room, knocks over the books and vases, and gets dirt everywhere&mdash;but not recognizable dog tracks, because he&rsquo;s wearing those boots. Then he runs out through the window.&rdquo;<br /><br />There&rsquo;s a lengthy silence as you all process this.<br /><br />&ldquo;So my husband&rsquo;s affair had nothing to do with this?&rdquo; asks Melissa.<br />
<br />Everyone turns to look at her&mdash;but Nathan chokes on his coffee. When he&rsquo;s regained his breath, he says &ldquo;You&mdash;you knew about that?&rdquo;<br /><br />&ldquo;YOU knew about that?&rdquo; says Melissa, incredulous.<br /><br />There&rsquo;s another silence.<br /><br />Melissa is the one to finally break it. &ldquo;Not until twenty minutes ago,&rdquo; she says. &ldquo;I received a call from a woman called Ms. Giles, who, herself, had only learned he was married earlier today, and thought I ought to know.&rdquo; She shakes her head. &ldquo;I always thought I&rsquo;d be furious if he finally crossed that line, but I can&rsquo;t even say I&rsquo;m terribly disappointed. I suppose I got over him years ago.&rdquo;<br /><br />Wordlessly, Nathan reaches into his pocket, pulls up something on his phone, and hands it to Melissa. She reads it silently, and then hands it to Frances, who, after reading it, hands it to you.<br /><br />It&rsquo;s an email sent three days ago, from Nathan to Victor.<br />&nbsp; &nbsp;&nbsp;<br /><i>Victor&mdash;<br />I found out about your side piece. You have a week to tell Mom everything, or I will. And if she decides to divorce you over this, I will be fully covering her legal and medical bills.<br />Happy New Years you hypocritical skeev,<br />Nathan</i><br />
<br />Nathan sighs. &ldquo;We talked about it after I got here yesterday. He offered to make me his sole beneficiary if I kept quiet, and I told him to go&mdash;uh, that I wouldn&rsquo;t agree to that. So he said he was going to cut me off completely.&rdquo; He crosses his arms. &ldquo;As if that was a threat. I make twice as much as he does and this house is a junkyard.&rdquo;<br /><br />&ldquo;All the same, the gesture is not lost on me,&rdquo; says Melissa, and for maybe half a second you think you see Nathan smile.<br />
<br />***<br /><br />Things start going a little better after that. By dinner time, Nathan has finished handling the work emergency he was apparently dealing with, Melissa has coached Frances on talking to her parents about her major, and Frances has signed herself and Peanut up for behavioral training.<br /><br />The next day the roads have been clearned and the police arrive and perform their own assessment of the scene. The police detective agrees with your conclusions, and offers to write you a letter of recommendation in case you ever need to land another private detective job solving a mystery in an old victorian house isolated during a snowstorm.<br><br><b>Instead of updating your theories & notes, please briefly answer the following question: How effective do you think you were at solving the mystery?</b></p>`;

